### ISSUE TITLE
2.5-prerelease uses Porcupine wake words from wrong architecture on Raspberry Pi

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-wake-porcupine-hermes#1]
I'm testing the `rhasspy/rhasspy:2.5.0-pre` Docker container on a freshly installed Raspbian on a Raspberry Pi 3. When I enable Porcupine as a wake word, it seems it picks up wake word files from the wrong architecture:

```
2020-03-07 18:36:20,917 INFO spawned: 'wake_word' with pid 5762                                          
DEBUG:__main__:Namespace(debug=True, host='localhost', keyword=['porcupine.ppn'], keyword_dir=['/profiles
/en/porcupine'], library=None, model=None, port=12183, sensitivity=['0.5'], siteId=['default'], stdin_aud
io=False, udp_audio_port=None, wakewordId=None)                                                          
DEBUG:__main__:Loading porcupine (kw=['/usr/lib/rhasspy-voltron/rhasspy-wake-porcupine-hermes/rhasspywake
_porcupine_hermes/porcupine/resources/keyword_files/linux/porcupine.ppn'], kwdirs=['/profiles/en/porcupin
e', '/usr/lib/rhasspy-voltron/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine/resour
ces/keyword_files/linux'], sensitivity=[0.5], library=/usr/lib/rhasspy-voltron/rhasspy-wake-porcupine-her
mes/rhasspywake_porcupine_hermes/porcupine/lib/raspberry-pi/cortex-a53/libpv_porcupine.so, model=/usr/lib
/rhasspy-voltron/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine/lib/common/porcupi$
e_params.pv)                                                                                             DEBUG:__main__:Shutting down                                                                             
[ERROR] keyword file has incorrect format or belongs to a different platform                             
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'                                           
Traceback (most recent call last):                                                                       
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                   
    "__main__", mod_spec)                                                                                
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code                                              
    exec(code, run_globals)                                                                              
  File "/usr/lib/rhasspy-voltron/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py"$
 line 212, in <module>                                                                                   
    main()                                                                                               
  File "/usr/lib/rhasspy-voltron/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py"$
 line 144, in main                                                                                       
    sensitivities=sensitivities,                                                                         
  File "/usr/lib/rhasspy-voltron/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine.py$
, line 124, in __init__                                                                                  
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]("Initialization failed")                           
ValueError: Initialization failed                                                                        
2020-03-07 18:36:21,999 INFO success: wake_word entered RUNNING state, process has stayed up for > than $
 seconds (startsecs)                                                                                     
2020-03-07 18:36:22,000 INFO exited: wake_word (exit status 1; not expected)
```

Note that both the `kw` and `kwdirs` parameters refer to the `linux` directory instead of `raspberrypi`.

**Comment by koenvervloesem** [comment]
I investigated further, this time with a standalone rhasspy-wake-porcupine-hermes to have finer control over the debugging process. I see the same error here, but I noticed there's something else going on: the ppn files in this repository are [96 bytes](https://github.com/rhasspy/rhasspy-wake-porcupine-hermes/blob/master/rhasspywake_porcupine_hermes/porcupine/resources/keyword_files/raspberrypi/porcupine.ppn), while the corresponding ppn files in the Porcupine repository are [3.07 KB](https://github.com/Picovoice/porcupine/blob/master/resources/keyword_files/raspberry-pi/porcupine_raspberry-pi.ppn).

When I try the ppn file from the Porcupine directory, I get the following error:

```
$ ./bin/rhasspy-wake-porcupine-hermes --keyword-dir . --keyword porcupine_raspberry-pi.ppn                                                                     
[ERROR] keyword file belongs to a different version of the library                                      
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'                                          
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main                                  
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code                                             
    exec(code, run_globals)
  File "/home/pi/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 212, in <module>
    main()
  File "/home/pi/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 144, in main
    sensitivities=sensitivities,
  File "/home/pi/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine.py", line 124, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]("Initialization failed")                          
ValueError: Initialization failed
```

**Comment by koenvervloesem** [comment]
Found it. Fixed picking up the wrong directory in https://github.com/rhasspy/rhasspy-wake-porcupine-hermes/commit/1104898de405874d8b303c36c651d6b4c3d29328.

But is the difference in file size of the ppn files right? It seems to work, though.

**Comment by synesthesiam** [comment]
There was some [big change](https://github.com/Picovoice/porcupine/commit/f5660d43d7b565196151cffb172cfcb715887b9f) recently with porcupine. I wonder if this caused the shift to larger wake words?

**Comment by Tooa** [comment]
@koenvervloesem looks like we can close this as https://github.com/rhasspy/rhasspy-wake-porcupine-hermes/commit/1104898de405874d8b303c36c651d6b4c3d29328 seems to fix the issue. Am I right?

**Comment by koenvervloesem** [comment]
Yes, this can be closed, thanks for the reminder!
