### ISSUE TITLE
Support German keywords

### ISSUE THREAD

**Issue by christophfroeschl** [rhasspy/rhasspy-wake-porcupine-hermes#7]
At the moment it is possible to place custom key-words into the porcpuine folder in your profile. This works great for English profile as the porcupine model is set to english. For a German key-word file like one under: https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files_de/raspberry-pi it fails with
`[ERROR] Keyword files (.PPN) and model file (.PV) should belong to the same language. Keyword files belongs to 'de' while model file belongs to 'en'.`

The reason for this is that in the docker-file you only copy the english model `COPY porcupine/lib/common/porcupine_params.pv /porcupine/`. However for german the german model https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params_de.pv is required.

Any chance this can be fixed?

**Comment by synesthesiam** [comment]
With the switch over to the pvporcupine Python package, I'm hoping this is now fixed (since it's no longer a manual process). Please re-open if it's still a problem.

**Comment by AvatarStartup** [comment]
Hi everyone, I had the same issue but in spanish language:

Keyword files (.PPN) and model file (.PV) should belong to the same language. Keyword files belongs to 'es' while model file belongs to 'en'.

Traceback (most recent call last):
  File "/home/cesarisaac/Documentos/Startup/Picovoice/voicedetectorcomputadora.py", line 13, in <module>
    porcupine = pvporcupine.create(keyword_paths=['/home/cesarisaac/Documentos/Startup/Picovoice/computadora.ppn'], model_path=['/home/cesarisaac/Documentos/Startup/Picovoice/porcupine_params_es.pv'])
  File "/usr/local/lib/python3.6/dist-packages/pvporcupine/__init__.py", line 68, in create
    sensitivities=sensitivities)
  File "/usr/local/lib/python3.6/dist-packages/pvporcupine/porcupine.py", line 62, in __init__
    if not os.path.exists(model_path):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
[Finished in 398ms with exit code 1]
[cmd: ['python3', '-u', '/home/cesarisaac/Documentos/Startup/Picovoice/voicedetectorcomputadora.py']]
[dir: /home/cesarisaac/Documentos/Startup/Picovoice]
[path: /home/cesarisaac/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin]

What can we do? Thanks a lot!!!

**Comment by asmirnou** [comment]
This can be done in the latest porcupine version, which is supported in the following PR: https://github.com/rhasspy/rhasspy-supervisor/pull/11. Can be tried by building from sources.
